version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: event-indexer-postgres
    environment:
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: indexer_password
      POSTGRES_DB: event_indexer
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U indexer -d event_indexer"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - indexer-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: event-indexer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - indexer-network

  # Ganache - Local Ethereum Test Network
  ganache:
    image: trufflesuite/ganache:latest
    container_name: event-indexer-ganache
    ports:
      - "8545:8545"
    command: >
      --mnemonic "test test test test test test test test test test test junk"
      --accounts 10
      --defaultBalanceEther 1000
      --gasLimit 12000000
      --gasPrice 20000000000
      --networkId 1337
      --chain.chainId 1337
      --host 0.0.0.0
      --port 8545
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - indexer-network

  # Adminer - Database Management UI
  adminer:
    image: adminer:latest
    container_name: event-indexer-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - indexer-network

  # Migration Service (runs migrations and exits)
  migrate:
    image: migrate/migrate:latest
    container_name: event-indexer-migrate
    volumes:
      - ./migrations:/migrations
    command: >
      -path=/migrations
      -database="postgres://indexer:indexer_password@postgres:5432/event_indexer?sslmode=disable"
      up
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - indexer-network
    profiles:
      - tools

networks:
  indexer-network:
    driver: bridge
    name: event-indexer-network

volumes:
  postgres_data:
    name: event-indexer-postgres-data
  redis_data:
    name: event-indexer-redis-data

